#%RAML 1.0 DataType
type: object
description: data types
properties:
          "id" : integer
          "tite" : string
          "content" : string
          "createdAt": time-only
          "updatedAt" : time-only